# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
# Copyright 2019 free5GC.org
#
# SPDX-License-Identifier: Apache-2.0



info:
  version: 1.0.0
  description: SMF initial local configuration

configuration:
  enableDBStore: false
  enableUPFAdapter: true
  debugProfilePort: 5001
  mongodb:
    name: sdcore_smf
    url: "mongodb://mongodb-arbiter-headless"
  kafkaInfo:
    brokerUri: "sd-core-kafka-headless"
    brokerPort: 9092
    topicName: "sdcore-data-source-smf"
  staticIpInfo:
    - dnn: internet_1
      imsiIpInfo:
        supi-123456789012341: "1.1.1.1"
        supi-123456789012342: "2.2.2.2"
        supi-123456789012343: "3.3.3.3"
        supi-123456789012344: "4.4.4.4"
    - dnn: internet_2
      imsiIpInfo:
        supi-123456789012345: "5.5.5.5"
        supi-123456789012346: "6.6.6.6"
        supi-123456789012347: "7.7.7.7"
        supi-123456789012348: "8.8.8.8"
  smfName: SMF # the name of this SMF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: smf # IP used to register to NRF
    bindingIPv4: smf  # IP used to bind the service
    port: 29502 # Port used to bind the service
    tls: # the local path of TLS key
      key: /support/TLS/smf.key # SMF TLS Certificate
      pem: /support/TLS/smf.pem # SMF TLS Private key
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
    - nsmf-pdusession # Nsmf_PDUSession service
    - nsmf-event-exposure # Nsmf_EventExposure service
    - nsmf-oam # OAM service
  pfcp: # the IP address of N4 interface on this SMF (PFCP)
    addr: smf
  nrfUri: http://nrf:29510 # a valid URI of NRF

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  SMF:
    debugLevel: debug
    ReportCaller: false
  NAS:
    debugLevel: debug
    ReportCaller: false
  NGAP:
    debugLevel: debug
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: debug
    ReportCaller: false
  OpenApi:
    debugLevel: debug
    ReportCaller: false
  PFCP:
    debugLevel: debug
    ReportCaller: false
